[package]
name = "game"
version = "0.1.0"
edition = "2021"

[dependencies]
raylib = "3.7.0"

[dependencies.game-macros]
path = "../game-macros/"

[dependencies.tokio]
version = "1.15.0"
features = ["macros", "rt-multi-thread"]
